export const CARDS = [
  // PR, PR+

  {
    id: 70,
    alias: "shinshinkiei",
    name: "新進気鋭",
    rarity: "PR",
    plan: "sense",
    idol: "saki",
    unique: true,
  },
  {
    id: 71,
    alias: "shinshinkiei_plus",
    name: "新進気鋭+",
    rarity: "PR+",
    plan: "sense",
    idol: "saki",
    unique: true,
  },
  {
    id: 72,
    alias: "ijippari",
    name: "意地っ張り",
    rarity: "PR",
    plan: "sense",
    idol: "temari",
    unique: true,
  },
  {
    id: 73,
    alias: "ijippari_plus",
    name: "意地っ張り+",
    rarity: "PR+",
    plan: "sense",
    idol: "temari",
    unique: true,
  },
  {
    id: 74,
    alias: "littleprince",
    name: "リトル・プリンス",
    rarity: "PR",
    plan: "sense",
    idol: "mao",
    unique: true,
  },
  {
    id: 75,
    alias: "littleprince_plus",
    name: "リトル・プリンス+",
    rarity: "PR+",
    plan: "sense",
    idol: "mao",
    unique: true,
  },
  {
    id: 76,
    alias: "houyouryoku",
    name: "包容力",
    rarity: "PR",
    plan: "sense",
    idol: "rinami",
    unique: true,
  },
  {
    id: 77,
    alias: "houyouryoku_plus",
    name: "包容力+",
    rarity: "PR+",
    plan: "sense",
    idol: "rinami",
    unique: true,
  },
  {
    id: 78,
    alias: "friendly",
    name: "フレンドリー",
    rarity: "PR",
    plan: "sense",
    idol: "sumika",
    unique: true,
  },
  {
    id: 79,
    alias: "friendly_plus",
    name: "フレンドリー+",
    rarity: "PR+",
    plan: "sense",
    idol: "sumika",
    unique: true,
  },
  {
    id: 80,
    alias: "arbeiter",
    name: "アルバイター",
    rarity: "PR",
    plan: "logic",
    idol: "kotone",
    unique: true,
  },
  {
    id: 81,
    alias: "arbeiter_plus",
    name: "アルバイター+",
    rarity: "PR+",
    plan: "logic",
    idol: "kotone",
    unique: true,
  },
  {
    id: 82,
    alias: "choukougakurekiidol",
    name: "超高学歴アイドル",
    rarity: "PR",
    plan: "logic",
    idol: "hiro",
    unique: true,
  },
  {
    id: 83,
    alias: "choukougakurekiidol_plus",
    name: "超高学歴アイドル+",
    rarity: "PR+",
    plan: "logic",
    idol: "hiro",
    unique: true,
  },
  {
    id: 84,
    alias: "uchikikeishoujo",
    name: "内気系少女",
    rarity: "PR",
    plan: "logic",
    idol: "lilja",
    unique: true,
  },
  {
    id: 85,
    alias: "uchikikeishoujo_plus",
    name: "内気系少女+",
    rarity: "PR+",
    plan: "logic",
    idol: "lilja",
    unique: true,
  },
  {
    id: 86,
    alias: "genkiippai",
    name: "元気いっぱい",
    rarity: "PR",
    plan: "logic",
    idol: "china",
    unique: true,
  },
  {
    id: 87,
    alias: "genkiippai_plus",
    name: "元気いっぱい+",
    rarity: "PR+",
    plan: "logic",
    idol: "china",
    unique: true,
  },
  {
    id: 88,
    alias: "mikannotaiki",
    name: "未完の大器",
    rarity: "PR",
    plan: "logic",
    idol: "ume",
    unique: true,
  },
  {
    id: 89,
    alias: "mikannotaiki_plus",
    name: "未完の大器+",
    rarity: "PR+",
    plan: "logic",
    idol: "ume",
    unique: true,
  },

  // PSR, PSR+

  {
    id: 160,
    alias: "ichibanwayuzuranai",
    name: "一番は譲らない",
    rarity: "PSR",
    plan: "sense",
    idol: "saki",
    unique: true,
  },
  {
    id: 161,
    alias: "ichibanwayuzuranai_plus",
    name: "一番は譲らない+",
    rarity: "PSR+",
    plan: "sense",
    idol: "saki",
    unique: true,
  },
  {
    id: 162,
    alias: "lonewolf",
    name: "ローン・ウルフ",
    rarity: "PSR",
    plan: "sense",
    idol: "temari",
    unique: true,
  },
  {
    id: 163,
    alias: "lonewolf_plus",
    name: "ローン・ウルフ+",
    rarity: "PSR+",
    plan: "sense",
    idol: "temari",
    unique: true,
  },
  {
    id: 164,
    alias: "rashisa",
    name: "らしさ",
    rarity: "PSR",
    plan: "sense",
    idol: "mao",
    unique: true,
  },
  {
    id: 165,
    alias: "rashisa_plus",
    name: "らしさ+",
    rarity: "PSR+",
    plan: "sense",
    idol: "mao",
    unique: true,
  },
  {
    id: 166,
    alias: "yorisoukimochi",
    name: "寄り添う気持ち",
    rarity: "PSR",
    plan: "sense",
    idol: "rinami",
    unique: true,
  },
  {
    id: 167,
    alias: "yorisoukimochi_plus",
    name: "寄り添う気持ち+",
    rarity: "PSR+",
    plan: "sense",
    idol: "rinami",
    unique: true,
  },
  {
    id: 168,
    alias: "yuukinoippo",
    name: "勇気の一歩",
    rarity: "PSR",
    plan: "sense",
    idol: "sumika",
    unique: true,
  },
  {
    id: 169,
    alias: "yuukinoippo_plus",
    name: "勇気の一歩+",
    rarity: "PSR+",
    plan: "sense",
    idol: "sumika",
    unique: true,
  },
  {
    id: 170,
    alias: "colorfulcute",
    name: "Colorful Cute!",
    rarity: "PSR",
    plan: "logic",
    idol: "kotone",
    unique: true,
  },
  {
    id: 171,
    alias: "colorfulcute_plus",
    name: "Colorful Cute!+",
    rarity: "PSR+",
    plan: "logic",
    idol: "kotone",
    unique: true,
  },
  {
    id: 172,
    alias: "kurushiinogasuki",
    name: "苦しいのが好き",
    rarity: "PSR",
    plan: "logic",
    idol: "hiro",
    unique: true,
  },
  {
    id: 173,
    alias: "kurushiinogasuki_plus",
    name: "苦しいのが好き+",
    rarity: "PSR+",
    plan: "logic",
    idol: "hiro",
    unique: true,
  },
  {
    id: 174,
    alias: "junpakunoyousei",
    name: "純白の妖精",
    rarity: "PSR",
    plan: "logic",
    idol: "lilja",
    unique: true,
  },
  {
    id: 175,
    alias: "junpakunoyousei_plus",
    name: "純白の妖精+",
    rarity: "PSR+",
    plan: "logic",
    idol: "lilja",
    unique: true,
  },
  {
    id: 176,
    alias: "isshokenmei",
    name: "いっしょけんめい",
    rarity: "PSR",
    plan: "logic",
    idol: "china",
    unique: true,
  },
  {
    id: 177,
    alias: "isshokenmei_plus",
    name: "いっしょけんめい+",
    rarity: "PSR+",
    plan: "logic",
    idol: "china",
    unique: true,
  },
  {
    id: 178,
    alias: "datouoneechan",
    name: "打倒お姉ちゃん",
    rarity: "PSR",
    plan: "logic",
    idol: "ume",
    unique: true,
  },
  {
    id: 179,
    alias: "datouoneechan_plus",
    name: "打倒お姉ちゃん+",
    rarity: "PSR+",
    plan: "logic",
    idol: "ume",
    unique: true,
  },

  // PSSR, PSSR+

  {
    id: 236,
    alias: "zettainimakenai",
    name: "絶対に負けない",
    rarity: "PSSR",
    plan: "sense",
    idol: "saki",
    unique: true,
  },
  {
    id: 237,
    alias: "zettainimakenai_plus",
    name: "絶対に負けない+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "saki",
    unique: true,
  },
  {
    id: 238,
    alias: "sorezorenomichi",
    name: "それぞれの道",
    rarity: "PSSR",
    plan: "sense",
    idol: "temari",
    unique: true,
  },
  {
    id: 239,
    alias: "sorezorenomichi_plus",
    name: "それぞれの道+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "temari",
    unique: true,
  },
  {
    id: 240,
    alias: "seisounohanagata",
    name: "盛装の華形",
    rarity: "PSSR",
    plan: "sense",
    idol: "mao",
    unique: true,
  },
  {
    id: 241,
    alias: "seisounohanagata_plus",
    name: "盛装の華形+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "mao",
    unique: true,
  },
  {
    id: 242,
    alias: "kyorikan",
    name: "距離感",
    rarity: "PSSR",
    plan: "sense",
    idol: "rinami",
    unique: true,
  },
  {
    id: 243,
    alias: "kyorikan_plus",
    name: "距離感+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "rinami",
    unique: true,
  },
  {
    id: 244,
    alias: "onemorestep",
    name: "ワンモアステップ",
    rarity: "PSSR",
    plan: "sense",
    idol: "sumika",
    unique: true,
  },
  {
    id: 245,
    alias: "onemorestep_plus",
    name: "ワンモアステップ+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "sumika",
    unique: true,
  },
  {
    id: 246,
    alias: "adrenalinezenkai",
    name: "アドレナリン全開",
    rarity: "PSSR",
    plan: "sense",
    idol: "kotone",
    unique: true,
  },
  {
    id: 247,
    alias: "adrenalinezenkai_plus",
    name: "アドレナリン全開+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "kotone",
    unique: true,
  },
  {
    id: 248,
    alias: "hinyarihitoyasumi",
    name: "ひんやり一休み",
    rarity: "PSSR",
    plan: "sense",
    idol: "mao",
    unique: true,
  },
  {
    id: 249,
    alias: "hinyarihitoyasumi_plus",
    name: "ひんやり一休み+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "mao",
    unique: true,
  },
  {
    id: 250,
    alias: "yosomiwadame",
    name: "よそ見はダメ♪",
    rarity: "PSSR",
    plan: "logic",
    idol: "kotone",
    unique: true,
  },
  {
    id: 251,
    alias: "yosomiwadame_plus",
    name: "よそ見はダメ♪+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "kotone",
    unique: true,
  },
  {
    id: 252,
    alias: "honkinoshumi",
    name: "本気の趣味",
    rarity: "PSSR",
    plan: "logic",
    idol: "hiro",
    unique: true,
  },
  {
    id: 253,
    alias: "honkinoshumi_plus",
    name: "本気の趣味+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "hiro",
    unique: true,
  },
  {
    id: 254,
    alias: "moukowakunaikara",
    name: "もう怖くないから",
    rarity: "PSSR",
    plan: "logic",
    idol: "lilja",
    unique: true,
  },
  {
    id: 255,
    alias: "moukowakunaikara_plus",
    name: "もう怖くないから+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "lilja",
    unique: true,
  },
  {
    id: 256,
    alias: "ojousamanoharebutai",
    name: "お嬢様の晴れ舞台",
    rarity: "PSSR",
    plan: "logic",
    idol: "china",
    unique: true,
  },
  {
    id: 257,
    alias: "ojousamanoharebutai_plus",
    name: "お嬢様の晴れ舞台+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "china",
    unique: true,
  },
  {
    id: 258,
    alias: "karamaruomoi",
    name: "絡まる想い",
    rarity: "PSSR",
    plan: "logic",
    idol: "temari",
    unique: true,
  },
  {
    id: 259,
    alias: "karamaruomoi_plus",
    name: "絡まる想い+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "temari",
    unique: true,
  },
  {
    id: 260,
    alias: "okkinaonigiri",
    name: "おっきなおにぎり",
    rarity: "PSSR",
    plan: "logic",
    idol: "ume",
    unique: true,
  },
  {
    id: 261,
    alias: "okkinaonigiri_plus",
    name: "おっきなおにぎり+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "ume",
    unique: true,
  },
  {
    id: 262,
    alias: "pow",
    name: "POW！",
    rarity: "PSSR",
    plan: "logic",
    idol: "saki",
    unique: true,
  },
  {
    id: 263,
    alias: "pow_plus",
    name: "POW！+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "saki",
    unique: true,
  },
  {
    id: 264,
    alias: "hirusagarinosoyokaze",
    name: "昼下がりのそよ風",
    rarity: "PSSR",
    plan: "logic",
    idol: "sumika",
    unique: true,
  },
  {
    id: 265,
    alias: "hirusagarinosoyokaze_plus",
    name: "昼下がりのそよ風+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "sumika",
    unique: true,
  },
  {
    id: 308,
    alias: "nyuudougumotokimi",
    name: "入道雲と、きみ",
    rarity: "PSSR",
    plan: "sense",
    idol: "rinami",
    unique: true,
  },
  {
    id: 309,
    alias: "nyuudougumotokimi_plus",
    name: "入道雲と、きみ+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "rinami",
    unique: true,
  },

  // SPSR, SPSR+

  {
    id: 180,
    alias: "oneechandamono",
    name: "お姉ちゃんだもの！",
    rarity: "SPSR",
    unique: true,
  },
  {
    id: 181,
    alias: "oneechandamono_plus",
    name: "お姉ちゃんだもの！+",
    rarity: "SPSR+",
    unique: true,
  },
  {
    id: 182,
    alias: "oatsuishisen",
    name: "おアツイ視線",
    rarity: "SPSR",
    unique: true,
  },
  {
    id: 183,
    alias: "oatsuishisen_plus",
    name: "おアツイ視線+",
    rarity: "SPSR+",
    unique: true,
  },
  {
    id: 184,
    alias: "goshidougobentatsu",
    name: "ご指導ご鞭撻",
    rarity: "SPSR",
    unique: true,
  },
  {
    id: 185,
    alias: "goshidougobentatsu_plus",
    name: "ご指導ご鞭撻+",
    rarity: "SPSR+",
    unique: true,
  },
  {
    id: 186,
    alias: "stretchdangi",
    name: "ストレッチ談義",
    rarity: "SPSR",
    unique: true,
  },
  {
    id: 187,
    alias: "stretchdangi_plus",
    name: "ストレッチ談義+",
    rarity: "SPSR+",
    unique: true,
  },
  {
    id: 188,
    alias: "zenryokusupport",
    name: "全力サポート",
    rarity: "SPSR",
    unique: true,
  },
  {
    id: 189,
    alias: "zenryokusupport_plus",
    name: "全力サポート+",
    rarity: "SPSR+",
    unique: true,
  },
  {
    id: 190,
    alias: "kimegaodejidori",
    name: "キメ顔で自撮り",
    rarity: "SPSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 191,
    alias: "kimegaodejidori_plus",
    name: "キメ顔で自撮り+",
    rarity: "SPSR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 192,
    alias: "nanikiiteruno",
    name: "なに聴いてるの？",
    rarity: "SPSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 193,
    alias: "nanikiiteruno_plus",
    name: "なに聴いてるの？+",
    rarity: "SPSR+",
    plan: "logic",
    unique: true,
  },

  // SPSSR, SPSSR+

  {
    id: 266,
    alias: "hanamoyukisetsu",
    name: "花萌ゆ季節",
    rarity: "SPSSR",
    unique: true,
  },
  {
    id: 267,
    alias: "hanamoyukisetsu_plus",
    name: "花萌ゆ季節+",
    rarity: "SPSSR+",
    unique: true,
  },
  {
    id: 268,
    alias: "hidamarinoseitokaishitsu",
    name: "陽だまりの生徒会室",
    rarity: "SPSSR",
    unique: true,
  },
  {
    id: 269,
    alias: "hidamarinoseitokaishitsu_plus",
    name: "陽だまりの生徒会室+",
    rarity: "SPSSR+",
    unique: true,
  },
  {
    id: 270,
    alias: "kokoronoalbum",
    name: "心のアルバム",
    rarity: "SPSSR",
    unique: true,
  },
  {
    id: 271,
    alias: "kokoronoalbum_plus",
    name: "心のアルバム+",
    rarity: "SPSSR+",
    unique: true,
  },
  {
    id: 272,
    alias: "teaparty",
    name: "ティーパーティ",
    rarity: "SPSSR",
    unique: true,
  },
  {
    id: 273,
    alias: "teaparty_plus",
    name: "ティーパーティ+",
    rarity: "SPSSR+",
    unique: true,
  },
  {
    id: 274,
    alias: "hikarinostage",
    name: "光のステージ",
    rarity: "SPSSR",
    unique: true,
  },
  {
    id: 275,
    alias: "hikarinostage_plus",
    name: "光のステージ+",
    rarity: "SPSSR+",
    unique: true,
  },
  {
    id: 276,
    alias: "shinseitokaibakutan",
    name: "新生徒会爆誕！",
    rarity: "SPSSR",
    unique: true,
  },
  {
    id: 277,
    alias: "shinseitokaibakutan_plus",
    name: "新生徒会爆誕！+",
    rarity: "SPSSR+",
    unique: true,
  },
  {
    id: 278,
    alias: "usureyukukabe",
    name: "薄れゆく壁",
    rarity: "SPSSR",
    unique: true,
  },
  {
    id: 279,
    alias: "usureyukukabe_plus",
    name: "薄れゆく壁+",
    rarity: "SPSSR+",
    unique: true,
  },
  {
    id: 280,
    alias: "mizutamaristep",
    name: "みずたまりステップ",
    rarity: "SPSSR",
    unique: true,
  },
  {
    id: 281,
    alias: "mizutamaristep_plus",
    name: "みずたまりステップ+",
    rarity: "SPSSR+",
    unique: true,
  },
  {
    id: 282,
    alias: "kenkasuruhodonakagaii",
    name: "喧嘩するほど仲がいい",
    rarity: "SPSSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 283,
    alias: "kenkasuruhodonakagaii_plus",
    name: "喧嘩するほど仲がいい+",
    rarity: "SPSSR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 284,
    alias: "damedamecooking",
    name: "ダメダメクッキング",
    rarity: "SPSSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 285,
    alias: "damedamecooking_plus",
    name: "ダメダメクッキング+",
    rarity: "SPSSR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 286,
    alias: "otomarimoubenkyou",
    name: "お泊り猛勉強",
    rarity: "SPSSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 287,
    alias: "otomarimoubenkyou_plus",
    name: "お泊り猛勉強+",
    rarity: "SPSSR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 310,
    alias: "hajikerumizushibuki",
    name: "はじける水しぶき",
    rarity: "SPSSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 311,
    alias: "hajikerumizushibuki_plus",
    name: "はじける水しぶき+",
    rarity: "SPSSR+",
    plan: "sense",
    unique: true,
  },

  // BR, BR+

  {
    id: 24,
    alias: "karuiashidori",
    name: "軽い足取り",
    rarity: "BR",
    plan: "sense",
  },
  {
    id: 25,
    alias: "karuiashidori_plus",
    name: "軽い足取り+",
    rarity: "BR+",
    plan: "sense",
  },
  {
    id: 26,
    alias: "aikyou",
    name: "愛嬌",
    rarity: "BR",
    plan: "sense",
  },
  {
    id: 27,
    alias: "aikyou_plus",
    name: "愛嬌+",
    rarity: "BR+",
    plan: "sense",
  },
  {
    id: 28,
    alias: "junbiundou",
    name: "準備運動",
    rarity: "BR",
    plan: "sense",
  },
  {
    id: 29,
    alias: "junbiundou_plus",
    name: "準備運動+",
    rarity: "BR+",
    plan: "sense",
  },
  {
    id: 30,
    alias: "fansa",
    name: "ファンサ",
    rarity: "BR",
    plan: "sense",
  },
  {
    id: 31,
    alias: "fansa_plus",
    name: "ファンサ+",
    rarity: "BR+",
    plan: "sense",
  },
  {
    id: 38,
    alias: "kyoumoohayou",
    name: "今日もおはよう",
    rarity: "BR",
    plan: "logic",
  },
  {
    id: 39,
    alias: "kyoumoohayou_plus",
    name: "今日もおはよう+",
    rarity: "BR+",
    plan: "logic",
  },
  {
    id: 40,
    alias: "yurufuwaoshaberi",
    name: "ゆるふわおしゃべり",
    rarity: "BR",
    plan: "logic",
  },
  {
    id: 41,
    alias: "yurufuwaoshaberi_plus",
    name: "ゆるふわおしゃべり+",
    rarity: "BR+",
    plan: "logic",
  },
  {
    id: 42,
    alias: "mousukoshidake",
    name: "もう少しだけ",
    rarity: "BR",
    plan: "logic",
  },
  {
    id: 43,
    alias: "mousukoshidake_plus",
    name: "もう少しだけ+",
    rarity: "BR+",
    plan: "logic",
  },
  {
    id: 52,
    alias: "balancekankaku",
    name: "バランス感覚",
    rarity: "BR",
    plan: "sense",
  },
  {
    id: 53,
    alias: "balancekankaku_plus",
    name: "バランス感覚+",
    rarity: "BR+",
    plan: "sense",
  },
  {
    id: 58,
    alias: "restart",
    name: "リスタート",
    rarity: "BR",
    plan: "logic",
  },
  {
    id: 59,
    alias: "restart_plus",
    name: "リスタート+",
    rarity: "BR+",
    plan: "logic",
  },
  {
    id: 60,
    alias: "eieio",
    name: "えいえいおー",
    rarity: "BR",
    plan: "logic",
  },
  {
    id: 61,
    alias: "eieio_plus",
    name: "えいえいおー+",
    rarity: "BR+",
    plan: "logic",
  },
  {
    id: 62,
    alias: "rhythmical",
    name: "リズミカル",
    rarity: "BR",
    plan: "logic",
  },
  {
    id: 63,
    alias: "rhythmical_plus",
    name: "リズミカル+",
    rarity: "BR+",
    plan: "logic",
  },

  // R, R+

  {
    id: 32,
    alias: "ikioimakase",
    name: "勢い任せ",
    rarity: "R",
    plan: "sense",
  },
  {
    id: 33,
    alias: "ikioimakase_plus",
    name: "勢い任せ+",
    rarity: "R+",
    plan: "sense",
  },
  {
    id: 34,
    alias: "hightouch",
    name: "ハイタッチ",
    rarity: "R",
    plan: "sense",
  },
  {
    id: 35,
    alias: "hightouch_plus",
    name: "ハイタッチ+",
    rarity: "R+",
    plan: "sense",
  },
  {
    id: 36,
    alias: "talktime",
    name: "トークタイム",
    rarity: "R",
    plan: "sense",
  },
  {
    id: 37,
    alias: "talktime_plus",
    name: "トークタイム+",
    rarity: "R+",
    plan: "sense",
  },
  {
    id: 44,
    alias: "tebyoushi",
    name: "手拍子",
    rarity: "R",
    plan: "logic",
  },
  {
    id: 45,
    alias: "tebyoushi_plus",
    name: "手拍子+",
    rarity: "R+",
    plan: "logic",
  },
  {
    id: 46,
    alias: "genkinaaisatsu",
    name: "元気な挨拶",
    rarity: "R",
    plan: "logic",
  },
  {
    id: 47,
    alias: "genkinaaisatsu_plus",
    name: "元気な挨拶+",
    rarity: "R+",
    plan: "logic",
  },
  {
    id: 48,
    alias: "kiaijuubun",
    name: "気合十分！",
    rarity: "R",
  },
  {
    id: 49,
    alias: "kiaijuubun_plus",
    name: "気合十分！+",
    rarity: "R+",
  },
  {
    id: 50,
    alias: "firststep",
    name: "ファーストステップ",
    rarity: "R",
    unique: true,
  },
  {
    id: 51,
    alias: "firststep_plus",
    name: "ファーストステップ+",
    rarity: "R+",
    unique: true,
  },
  {
    id: 54,
    alias: "rakkanteki",
    name: "楽観的",
    rarity: "R",
    plan: "sense",
  },
  {
    id: 55,
    alias: "rakkanteki_plus",
    name: "楽観的+",
    rarity: "R+",
    plan: "sense",
  },
  {
    id: 56,
    alias: "shinkokyuu",
    name: "深呼吸",
    rarity: "R",
    plan: "sense",
  },
  {
    id: 57,
    alias: "shinkokyuu_plus",
    name: "深呼吸+",
    rarity: "R+",
    plan: "sense",
  },
  {
    id: 64,
    alias: "omoidashiwarai",
    name: "思い出し笑い",
    rarity: "R",
    plan: "logic",
  },
  {
    id: 65,
    alias: "omoidashiwarai_plus",
    name: "思い出し笑い+",
    rarity: "R+",
    plan: "logic",
  },
  {
    id: 66,
    alias: "pastelkibun",
    name: "パステル気分",
    rarity: "R",
    plan: "logic",
  },
  {
    id: 67,
    alias: "pastelkibun_plus",
    name: "パステル気分+",
    rarity: "R+",
    plan: "logic",
  },
  {
    id: 68,
    alias: "hagemashi",
    name: "励まし",
    rarity: "R",
    plan: "logic",
  },
  {
    id: 69,
    alias: "hagemashi_plus",
    name: "励まし+",
    rarity: "R+",
    plan: "logic",
  },
  {
    id: 288,
    alias: "hitokokyuu",
    name: "ひと呼吸",
    rarity: "R",
    plan: "sense",
    unique: true,
  },
  {
    id: 289,
    alias: "hitokokyuu_plus",
    name: "ひと呼吸+",
    rarity: "R+",
    plan: "sense",
    unique: true,
  },
  {
    id: 290,
    alias: "shiawasenoomajinai",
    name: "幸せのおまじない",
    rarity: "R",
    plan: "logic",
  },
  {
    id: 291,
    alias: "shiawasenoomajinai_plus",
    name: "幸せのおまじない+",
    rarity: "R+",
    plan: "logic",
  },

  // BSR, BSR+

  {
    id: 92,
    alias: "kimepose",
    name: "決めポーズ",
    rarity: "BSR",
    plan: "sense",
  },
  {
    id: 93,
    alias: "kimepose_plus",
    name: "決めポーズ+",
    rarity: "BSR+",
    plan: "sense",
  },
  {
    id: 94,
    alias: "adlib",
    name: "アドリブ",
    rarity: "BSR",
    plan: "sense",
  },
  {
    id: 95,
    alias: "adlib_plus",
    name: "アドリブ+",
    rarity: "BSR+",
    plan: "sense",
  },
  {
    id: 96,
    alias: "jounetsuturn",
    name: "情熱ターン",
    rarity: "BSR",
    plan: "sense",
  },
  {
    id: 97,
    alias: "jounetsuturn_plus",
    name: "情熱ターン+",
    rarity: "BSR+",
    plan: "sense",
  },
  {
    id: 108,
    alias: "lovelywink",
    name: "ラブリーウインク",
    rarity: "BSR",
    plan: "logic",
  },
  {
    id: 109,
    alias: "lovelywink_plus",
    name: "ラブリーウインク+",
    rarity: "BSR+",
    plan: "logic",
  },
  {
    id: 110,
    alias: "arigatounokotoba",
    name: "ありがとうの言葉",
    rarity: "BSR",
    plan: "logic",
  },
  {
    id: 111,
    alias: "arigatounokotoba_plus",
    name: "ありがとうの言葉+",
    rarity: "BSR+",
    plan: "logic",
  },
  {
    id: 122,
    alias: "ganryoku",
    name: "眼力",
    rarity: "BSR",
    plan: "sense",
  },
  {
    id: 123,
    alias: "ganryoku_plus",
    name: "眼力+",
    rarity: "BSR+",
    plan: "sense",
  },
  {
    id: 124,
    alias: "daiseien",
    name: "大声援",
    rarity: "BSR",
    plan: "sense",
  },
  {
    id: 125,
    alias: "daiseien_plus",
    name: "大声援+",
    rarity: "BSR+",
    plan: "sense",
  },
  {
    id: 140,
    alias: "afureruomoide",
    name: "あふれる思い出",
    rarity: "BSR",
    plan: "logic",
  },
  {
    id: 141,
    alias: "afureruomoide_plus",
    name: "あふれる思い出+",
    rarity: "BSR+",
    plan: "logic",
  },
  {
    id: 142,
    alias: "fureai",
    name: "ふれあい",
    rarity: "BSR",
    plan: "logic",
  },
  {
    id: 143,
    alias: "fureai_plus",
    name: "ふれあい+",
    rarity: "BSR+",
    plan: "logic",
  },

  // SR, SR+

  {
    id: 90,
    alias: "zentoyouyou",
    name: "前途洋々",
    rarity: "SR",
  },
  {
    id: 91,
    alias: "zentoyouyou_plus",
    name: "前途洋々+",
    rarity: "SR+",
  },
  {
    id: 98,
    alias: "hiyaku",
    name: "飛躍",
    rarity: "SR",
    plan: "sense",
  },
  {
    id: 99,
    alias: "hiyaku_plus",
    name: "飛躍+",
    rarity: "SR+",
    plan: "sense",
  },
  {
    id: 100,
    alias: "shukufuku",
    name: "祝福",
    rarity: "SR",
    plan: "sense",
  },
  {
    id: 101,
    alias: "shukufuku_plus",
    name: "祝福+",
    rarity: "SR+",
    plan: "sense",
  },
  {
    id: 102,
    alias: "startdash",
    name: "スタートダッシュ",
    rarity: "SR",
    plan: "sense",
    unique: true,
  },
  {
    id: 103,
    alias: "startdash_plus",
    name: "スタートダッシュ+",
    rarity: "SR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 104,
    alias: "standplay",
    name: "スタンドプレー",
    rarity: "SR",
    plan: "sense",
    unique: true,
  },
  {
    id: 105,
    alias: "standplay_plus",
    name: "スタンドプレー+",
    rarity: "SR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 106,
    alias: "sprechchor",
    name: "シュプレヒコール",
    rarity: "SR",
    plan: "sense",
    unique: true,
  },
  {
    id: 107,
    alias: "sprechchor_plus",
    name: "シュプレヒコール+",
    rarity: "SR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 112,
    alias: "heartnoaizu",
    name: "ハートの合図",
    rarity: "SR",
    plan: "logic",
  },
  {
    id: 113,
    alias: "heartnoaizu_plus",
    name: "ハートの合図+",
    rarity: "SR+",
    plan: "logic",
  },
  {
    id: 114,
    alias: "kirameki",
    name: "キラメキ",
    rarity: "SR",
    plan: "logic",
    unique: true,
  },
  {
    id: 115,
    alias: "kirameki_plus",
    name: "キラメキ+",
    rarity: "SR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 116,
    alias: "minnadaisuki",
    name: "みんな大好き",
    rarity: "SR",
    plan: "logic",
    unique: true,
  },
  {
    id: 117,
    alias: "minnadaisuki_plus",
    name: "みんな大好き+",
    rarity: "SR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 118,
    alias: "idolsengen",
    name: "アイドル宣言",
    rarity: "SR",
    unique: true,
  },
  {
    id: 119,
    alias: "idolsengen_plus",
    name: "アイドル宣言+",
    rarity: "SR+",
    unique: true,
  },
  {
    id: 120,
    alias: "hightension",
    name: "ハイテンション",
    rarity: "SR",
  },
  {
    id: 121,
    alias: "hightension_plus",
    name: "ハイテンション+",
    rarity: "SR+",
  },
  {
    id: 126,
    alias: "enshutsukeikaku",
    name: "演出計画",
    rarity: "SR",
    plan: "sense",
    unique: true,
  },
  {
    id: 127,
    alias: "enshutsukeikaku_plus",
    name: "演出計画+",
    rarity: "SR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 128,
    alias: "negainochikara",
    name: "願いの力",
    rarity: "SR",
    plan: "sense",
    unique: true,
  },
  {
    id: 129,
    alias: "negainochikara_plus",
    name: "願いの力+",
    rarity: "SR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 130,
    alias: "shizukanaishi",
    name: "静かな意思",
    rarity: "SR",
    plan: "sense",
  },
  {
    id: 131,
    alias: "shizukanaishi_plus",
    name: "静かな意思+",
    rarity: "SR+",
    plan: "sense",
  },
  {
    id: 132,
    alias: "hajimarinoaizu",
    name: "始まりの合図",
    rarity: "SR",
    plan: "sense",
  },
  {
    id: 133,
    alias: "hajimarinoaizu_plus",
    name: "始まりの合図+",
    rarity: "SR+",
    plan: "sense",
  },
  {
    id: 134,
    alias: "iji",
    name: "意地",
    rarity: "SR",
    plan: "sense",
  },
  {
    id: 135,
    alias: "iji_plus",
    name: "意地+",
    rarity: "SR+",
    plan: "sense",
  },
  {
    id: 136,
    alias: "sonzaikan",
    name: "存在感",
    rarity: "SR",
    plan: "sense",
    unique: true,
  },
  {
    id: 137,
    alias: "sonzaikan_plus",
    name: "存在感+",
    rarity: "SR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 138,
    alias: "seikouenomichisuji",
    name: "成功への道筋",
    rarity: "SR",
    plan: "sense",
  },
  {
    id: 139,
    alias: "seikouenomichisuji_plus",
    name: "成功への道筋+",
    rarity: "SR+",
    plan: "sense",
  },
  {
    id: 144,
    alias: "shiawasenajikan",
    name: "幸せな時間",
    rarity: "SR",
    plan: "logic",
  },
  {
    id: 145,
    alias: "shiawasenajikan_plus",
    name: "幸せな時間+",
    rarity: "SR+",
    plan: "logic",
  },
  {
    id: 146,
    alias: "fancycharm",
    name: "ファンシーチャーム",
    rarity: "SR",
    plan: "logic",
    unique: true,
  },
  {
    id: 147,
    alias: "fancycharm_plus",
    name: "ファンシーチャーム+",
    rarity: "SR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 148,
    alias: "wakuwakugatomaranai",
    name: "ワクワクが止まらない",
    rarity: "SR",
    plan: "logic",
    unique: true,
  },
  {
    id: 149,
    alias: "wakuwakugatomaranai_plus",
    name: "ワクワクが止まらない+",
    rarity: "SR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 150,
    alias: "honbanzenya",
    name: "本番前夜",
    rarity: "SR",
    plan: "logic",
  },
  {
    id: 151,
    alias: "honbanzenya_plus",
    name: "本番前夜+",
    rarity: "SR+",
    plan: "logic",
  },
  {
    id: 152,
    alias: "hinatabokko",
    name: "ひなたぼっこ",
    rarity: "SR",
    plan: "logic",
    unique: true,
  },
  {
    id: 153,
    alias: "hinatabokko_plus",
    name: "ひなたぼっこ+",
    rarity: "SR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 154,
    alias: "imetore",
    name: "イメトレ",
    rarity: "SR",
    plan: "logic",
  },
  {
    id: 155,
    alias: "imetore_plus",
    name: "イメトレ+",
    rarity: "SR+",
    plan: "logic",
  },
  {
    id: 156,
    alias: "yarukiwamanten",
    name: "やる気は満点",
    rarity: "SR",
    plan: "logic",
  },
  {
    id: 157,
    alias: "yarukiwamanten_plus",
    name: "やる気は満点+",
    rarity: "SR+",
    plan: "logic",
  },
  {
    id: 158,
    alias: "yumemigokochi",
    name: "ゆめみごこち",
    rarity: "SR",
    plan: "logic",
    unique: true,
  },
  {
    id: 159,
    alias: "yumemigokochi_plus",
    name: "ゆめみごこち+",
    rarity: "SR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 292,
    alias: "tachiichicheck",
    name: "立ち位置チェック",
    rarity: "SR",
    plan: "sense",
  },
  {
    id: 293,
    alias: "tachiichicheck_plus",
    name: "立ち位置チェック+",
    rarity: "SR+",
    plan: "sense",
  },
  {
    id: 294,
    alias: "spotlight",
    name: "スポットライト",
    rarity: "SR",
    plan: "sense",
  },
  {
    id: 295,
    alias: "spotlight_plus",
    name: "スポットライト+",
    rarity: "SR+",
    plan: "sense",
  },
  {
    id: 296,
    alias: "tomerarenaiomoi",
    name: "止められない想い",
    rarity: "SR",
    plan: "logic",
    unique: true,
  },
  {
    id: 297,
    alias: "tomerarenaiomoi_plus",
    name: "止められない想い+",
    rarity: "SR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 298,
    alias: "otomegokoro",
    name: "止められない想い",
    rarity: "SR",
    plan: "logic",
    unique: true,
  },
  {
    id: 299,
    alias: "otomegokoro_plus",
    name: "止められない想い+",
    rarity: "SR+",
    plan: "logic",
    unique: true,
  },

  // SSR, SSR+

  {
    id: 194,
    alias: "callandresponse",
    name: "コール＆レスポンス",
    rarity: "SSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 195,
    alias: "callandresponse_plus",
    name: "コール＆レスポンス+",
    rarity: "SSR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 196,
    alias: "buzzword",
    name: "バズワード",
    rarity: "SSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 197,
    alias: "buzzword_plus",
    name: "バズワード+",
    rarity: "SSR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 198,
    alias: "jouju",
    name: "成就",
    rarity: "SSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 199,
    alias: "jouju_plus",
    name: "成就+",
    rarity: "SSR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 200,
    alias: "miwakunoperformance",
    name: "魅惑のパフォーマンス",
    rarity: "SSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 201,
    alias: "miwakunoperformance_plus",
    name: "魅惑のパフォーマンス+",
    rarity: "SSR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 202,
    alias: "200percentsmile",
    name: "200％スマイル",
    rarity: "SSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 203,
    alias: "200percentsmile_plus",
    name: "200％スマイル+",
    rarity: "SSR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 204,
    alias: "kaika",
    name: "開花",
    rarity: "SSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 205,
    alias: "kaika_plus",
    name: "開花+",
    rarity: "SSR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 206,
    alias: "todoite",
    name: "届いて！",
    rarity: "SSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 207,
    alias: "todoite_plus",
    name: "届いて！+",
    rarity: "SSR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 208,
    alias: "tvshutsuen",
    name: "テレビ出演",
    rarity: "SSR",
    unique: true,
  },
  {
    id: 209,
    alias: "tvshutsuen_plus",
    name: "テレビ出演+",
    rarity: "SSR+",
    unique: true,
  },
  {
    id: 210,
    alias: "kanaetaiyume",
    name: "叶えたい夢",
    rarity: "SSR",
    unique: true,
  },
  {
    id: 211,
    alias: "kanaetaiyume_plus",
    name: "叶えたい夢+",
    rarity: "SSR+",
    unique: true,
  },
  {
    id: 212,
    alias: "idoldamashii",
    name: "アイドル魂",
    rarity: "SSR",
    unique: true,
  },
  {
    id: 213,
    alias: "idoldamashii_plus",
    name: "アイドル魂+",
    rarity: "SSR+",
    unique: true,
  },
  {
    id: 214,
    alias: "shikirinaoshi",
    name: "仕切り直し",
    rarity: "SSR",
    unique: true,
  },
  {
    id: 215,
    alias: "shikirinaoshi_plus",
    name: "仕切り直し+",
    rarity: "SSR+",
    unique: true,
  },
  {
    id: 216,
    alias: "kokumintekiidol",
    name: "国民的アイドル",
    rarity: "SSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 217,
    alias: "kokumintekiidol_plus",
    name: "国民的アイドル+",
    rarity: "SSR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 218,
    alias: "miwakunoshisen",
    name: "魅惑の視線",
    rarity: "SSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 219,
    alias: "miwakunoshisen_plus",
    name: "魅惑の視線+",
    rarity: "SSR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 220,
    alias: "nariyamanaihakushu",
    name: "鳴り止まない拍手",
    rarity: "SSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 221,
    alias: "nariyamanaihakushu_plus",
    name: "鳴り止まない拍手+",
    rarity: "SSR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 222,
    alias: "tenshinranman",
    name: "天真爛漫",
    rarity: "SSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 223,
    alias: "tenshinranman_plus",
    name: "天真爛漫+",
    rarity: "SSR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 224,
    alias: "watashigastar",
    name: "私がスター",
    rarity: "SSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 225,
    alias: "watashigastar_plus",
    name: "私がスター+",
    rarity: "SSR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 226,
    alias: "hoshikuzusensation",
    name: "星屑センセーション",
    rarity: "SSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 227,
    alias: "hoshikuzusensation_plus",
    name: "星屑センセーション+",
    rarity: "SSR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 228,
    alias: "notenohashinoketsui",
    name: "ノートの端の決意",
    rarity: "SSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 229,
    alias: "notenohashinoketsui_plus",
    name: "ノートの端の決意+",
    rarity: "SSR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 230,
    alias: "tegakinomessage",
    name: "手書きのメッセージ",
    rarity: "SSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 231,
    alias: "tegakinomessage_plus",
    name: "手書きのメッセージ+",
    rarity: "SSR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 232,
    alias: "tokimeki",
    name: "トキメキ",
    rarity: "SSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 233,
    alias: "tokimeki_plus",
    name: "トキメキ+",
    rarity: "SSR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 234,
    alias: "nijiirodreamer",
    name: "虹色ドリーマー",
    rarity: "SSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 235,
    alias: "nijiirodreamer_plus",
    name: "虹色ドリーマー+",
    rarity: "SSR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 300,
    alias: "shikounoentertainment",
    name: "至高のエンタメ",
    rarity: "SSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 301,
    alias: "shikounoentertainment_plus",
    name: "至高のエンタメ+",
    rarity: "SSR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 302,
    alias: "kakusei",
    name: "覚醒",
    rarity: "SSR",
    plan: "sense",
    unique: true,
  },
  {
    id: 303,
    alias: "kakusei_plus",
    name: "覚醒+",
    rarity: "SSR+",
    plan: "sense",
    unique: true,
  },
  {
    id: 304,
    alias: "kagayakukimie",
    name: "輝くキミへ",
    rarity: "SSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 305,
    alias: "kagayakukimie_plus",
    name: "輝くキミへ+",
    rarity: "SSR+",
    plan: "logic",
    unique: true,
  },
  {
    id: 306,
    alias: "anotokinoyakusoku",
    name: "あのとくの約束",
    rarity: "SSR",
    plan: "logic",
    unique: true,
  },
  {
    id: 307,
    alias: "anotokinoyakusoku_plus",
    name: "あのとくの約束+",
    rarity: "SSR+",
    plan: "logic",
    unique: true,
  },

  // N, N+, T

  {
    id: 1,
    alias: "appealnokihon",
    name: "アピールの基本",
    rarity: "N",
  },
  {
    id: 2,
    alias: "appealnokihon_plus",
    name: "アピールの基本+",
    rarity: "N+",
  },
  {
    id: 3,
    alias: "posenokihon",
    name: "ポーズの基本",
    rarity: "N",
  },
  {
    id: 4,
    alias: "posenokihon_plus",
    name: "ポーズの基本+",
    rarity: "N+",
  },
  {
    id: 5,
    alias: "chousen",
    name: "挑戦",
    rarity: "N",
    plan: "sense",
  },
  {
    id: 6,
    alias: "chousen_plus",
    name: "挑戦+",
    rarity: "N+",
    plan: "sense",
  },
  {
    id: 7,
    alias: "shikousakugo",
    name: "試行錯誤",
    rarity: "N",
    plan: "sense",
  },
  {
    id: 8,
    alias: "shikousakugo_plus",
    name: "試行錯誤+",
    rarity: "N+",
    plan: "sense",
  },
  {
    id: 9,
    alias: "kawaiishigusa",
    name: "可愛い仕草",
    rarity: "N",
    plan: "logic",
  },
  {
    id: 10,
    alias: "kawaiishigusa_plus",
    name: "可愛い仕草+",
    rarity: "N+",
    plan: "logic",
  },
  {
    id: 11,
    alias: "kibuntenkan",
    name: "気分転換",
    rarity: "N",
    plan: "logic",
  },
  {
    id: 12,
    alias: "kibuntenkan_plus",
    name: "気分転換+",
    rarity: "N+",
    plan: "logic",
  },
  {
    id: 13,
    alias: "hyougennokihon",
    name: "表現の基本",
    rarity: "N",
  },
  {
    id: 14,
    alias: "hyougennokihon_plus",
    name: "表現の基本+",
    rarity: "N+",
  },
  {
    id: 15,
    alias: "furumainokihon",
    name: "振る舞いの基本",
    rarity: "N",
    plan: "sense",
  },
  {
    id: 16,
    alias: "furumainokihon_plus",
    name: "振る舞いの基本+",
    rarity: "N+",
    plan: "sense",
  },
  {
    id: 17,
    alias: "hyoujounokihon",
    name: "表情の基本",
    rarity: "N",
    plan: "sense",
  },
  {
    id: 18,
    alias: "hyoujounokihon_plus",
    name: "表情の基本+",
    rarity: "N+",
    plan: "sense",
  },
  {
    id: 19,
    alias: "mesennokihon",
    name: "目線の基本",
    rarity: "N",
    plan: "logic",
  },
  {
    id: 20,
    alias: "mesennokihon_plus",
    name: "目線の基本+",
    rarity: "N+",
    plan: "logic",
  },
  {
    id: 21,
    alias: "ishikinokihon",
    name: "意識の基本",
    rarity: "N",
    plan: "logic",
  },
  {
    id: 22,
    alias: "ishikinokihon_plus",
    name: "意識の基本+",
    rarity: "N+",
    plan: "logic",
  },
  {
    id: 23,
    alias: "nemuke",
    name: "眠気",
    rarity: "T",
  },
];

export const CARDS_BY_ID = CARDS.reduce(
  (acc, cur) => ({
    ...acc,
    [cur.id]: cur,
  }),
  {}
);

export const MEMORABLE_CARDS = CARDS.filter(
  (card) => !["N", "N+", "T"].includes(card.rarity)
);

export const COST_BY_RARITY = {
  SPSR: 96,
  "SPSR+": 126,
  SPSSR: 96,
  "SPSSR+": 126,
  BR: 30,
  "BR+": 39,
  R: 45,
  "R+": 60,
  BSR: 75,
  "BSR+": 102,
  SR: 105,
  "SR+": 141,
  SSR: 150,
  "SSR+": 204,
};

export const DEFAULT_CARDS_BY_PLAN = {
  sense: [5, 7, 1, 1, 15, 15, 17, 17],
  logic: [9, 11, 19, 19, 21, 21, 13, 13],
};
