export const IDOLS = [
  {
    id: 33,
    alias: "saki_boomboompow",
    title: "Boom Boom Pow",
    name: "花海 咲季",
    plan: "logic",
    rarity: "SSR",
  },
  {
    id: 32,
    alias: "kotone_yellowbigbang",
    title: "Yellow Big Bang！",
    name: "藤田 ことね",
    plan: "sense",
    rarity: "SSR",
  },
  {
    id: 31,
    alias: "temari_ivy",
    title: "アイヴィ",
    name: "月村 手毬",
    plan: "logic",
    rarity: "SSR",
  },
  {
    id: 21,
    alias: "saki_fightingmyway",
    title: "Fighting My Way",
    name: "花海 咲季",
    plan: "sense",
    rarity: "SSR",
  },
  {
    id: 22,
    alias: "temari_lunasaymaybe",
    title: "Luna say maybe",
    name: "月村 手毬",
    plan: "sense",
    rarity: "SSR",
  },
  {
    id: 23,
    alias: "kotone_sekaiichikawaiiwatashi",
    title: "世界一可愛い私",
    name: "藤田 ことね",
    plan: "logic",
    rarity: "SSR",
  },
  {
    id: 24,
    alias: "mao_fluorite",
    title: "Fluorite",
    name: "有村 麻央",
    plan: "sense",
    rarity: "SSR",
  },
  {
    id: 25,
    alias: "lilja_hakusen",
    title: "白線",
    name: "葛城 リーリヤ",
    plan: "logic",
    rarity: "SSR",
  },
  {
    id: 26,
    alias: "china_wonderscale",
    title: "Wonder Scale",
    name: "倉本 千奈",
    plan: "logic",
    rarity: "SSR",
  },
  {
    id: 27,
    alias: "sumika_tamelieonestep",
    title: "Tame-Lie-One-Step",
    name: "紫雲 清夏",
    plan: "sense",
    rarity: "SSR",
  },
  {
    id: 28,
    alias: "hiro_koukei",
    title: "光景",
    name: "篠澤 広",
    plan: "logic",
    rarity: "SSR",
  },
  {
    id: 29,
    alias: "ume_therollingriceball",
    title: "The Rolling Riceball",
    name: "花海 佑芽",
    plan: "logic",
    rarity: "SSR",
  },
  {
    id: 30,
    alias: "rinami_clumsytrick",
    title: "clumsy trick",
    name: "姫崎 莉波",
    plan: "sense",
    rarity: "SSR",
  },
  {
    id: 11,
    alias: "saki_watashigaichiban",
    title: "わたしが一番！",
    name: "花海 咲季",
    plan: "sense",
    rarity: "SR",
  },
  {
    id: 12,
    alias: "temari_ippikiookami",
    title: "一匹狼",
    name: "月村 手毬",
    plan: "sense",
    rarity: "SR",
  },
  {
    id: 13,
    alias: "kotone_kawaiihajimemashita",
    title: "カワイイ♡はじめました",
    name: "藤田 ことね",
    plan: "logic",
    rarity: "SR",
  },
  {
    id: 14,
    alias: "mao_hajimariwakakkoyoku",
    title: "はじまりはカッコよく",
    name: "有村 麻央",
    plan: "sense",
    rarity: "SR",
  },
  {
    id: 15,
    alias: "lilja_hitotsufumidashitasakini",
    title: "一つ踏み出した先に",
    name: "葛城 リーリヤ",
    plan: "logic",
    rarity: "SR",
  },
  {
    id: 16,
    alias: "china_munewohatteippozutsu",
    title: "胸を張って一歩ずつ",
    name: "倉本 千奈",
    plan: "logic",
    rarity: "SR",
  },
  {
    id: 17,
    alias: "sumika_yumeenorestart",
    title: "夢へのリスタート",
    name: "紫雲 清夏",
    plan: "sense",
    rarity: "SR",
  },
  {
    id: 18,
    alias: "hiro_ichibanmuitenaikoto",
    title: "一番向いてないこと",
    name: "篠澤 広",
    plan: "logic",
    rarity: "SR",
  },
  {
    id: 19,
    alias: "ume_idolhajime",
    title: "アイドル、はじめっ！",
    name: "花海 佑芽",
    plan: "logic",
    rarity: "SR",
  },
  {
    id: 20,
    alias: "rinami_watashirashisanohajimari",
    title: "『私らしさ』のはじまり",
    name: "姫崎 莉波",
    plan: "sense",
    rarity: "SR",
  },
  {
    id: 1,
    alias: "saki_gakuenseikatsu",
    title: "学園生活",
    name: "花海 咲季",
    plan: "sense",
    rarity: "R",
  },
  {
    id: 2,
    alias: "temari_gakuenseikatsu",
    title: "学園生活",
    name: "月村 手毬",
    plan: "sense",
    rarity: "R",
  },
  {
    id: 3,
    alias: "kotone_gakuenseikatsu",
    title: "学園生活",
    name: "藤田 ことね",
    plan: "logic",
    rarity: "R",
  },
  {
    id: 4,
    alias: "mao_gakuenseikatsu",
    title: "学園生活",
    name: "有村 麻央",
    plan: "sense",
    rarity: "R",
  },
  {
    id: 5,
    alias: "lilja_gakuenseikatsu",
    title: "学園生活",
    name: "葛城 リーリヤ",
    plan: "logic",
    rarity: "R",
  },
  {
    id: 6,
    alias: "china_gakuenseikatsu",
    title: "学園生活",
    name: "倉本 千奈",
    plan: "logic",
    rarity: "R",
  },
  {
    id: 7,
    alias: "sumika_gakuenseikatsu",
    title: "学園生活",
    name: "紫雲 清夏",
    plan: "sense",
    rarity: "R",
  },
  {
    id: 8,
    alias: "hiro_gakuenseikatsu",
    title: "学園生活",
    name: "篠澤 広",
    plan: "logic",
    rarity: "R",
  },
  {
    id: 9,
    alias: "ume_gakuenseikatsu",
    title: "学園生活",
    name: "花海 佑芽",
    plan: "logic",
    rarity: "R",
  },
  {
    id: 10,
    alias: "rinami_gakuenseikatsu",
    title: "学園生活",
    name: "姫崎 莉波",
    plan: "sense",
    rarity: "R",
  },
];

export const IDOLS_BY_ID = IDOLS.reduce(
  (acc, cur) => ({
    ...acc,
    [cur.id]: cur,
  }),
  {}
);
