export const ITEMS = [
  // PR, PR+

  {
    id: 1,
    alias: "bakuonlion",
    name: "ばくおんライオン",
    rarity: "PR",
    plan: "sense",
    idol: "saki",
  },
  {
    id: 2,
    alias: "bakuonlion_plus",
    name: "ばくおんライオン+",
    rarity: "PR+",
    idol: "saki",
    plan: "sense",
  },
  {
    id: 3,
    alias: "hikkeistainlessbottle",
    name: "必携ステンレスボトル",
    rarity: "PR",
    plan: "sense",
    idol: "temari",
  },
  {
    id: 4,
    alias: "hikkeistainlessbottle_plus",
    name: "必携ステンレスボトル+",
    rarity: "PR+",
    plan: "sense",
    idol: "temari",
  },
  {
    id: 5,
    alias: "shinshifuuhandkerchief",
    name: "紳士風ハンカチーフ",
    rarity: "PR",
    plan: "sense",
    idol: "mao",
  },
  {
    id: 6,
    alias: "shinshifuuhandkerchief_plus",
    name: "紳士風ハンカチーフ+",
    rarity: "PR+",
    plan: "sense",
    idol: "mao",
  },
  {
    id: 7,
    alias: "itsumonomakepouch",
    name: "いつものメイクポーチ",
    rarity: "PR",
    plan: "sense",
    idol: "rinami",
  },
  {
    id: 8,
    alias: "itsumonomakepouch_plus",
    name: "いつものメイクポーチ+",
    rarity: "PR+",
    plan: "sense",
    idol: "rinami",
  },
  {
    id: 9,
    alias: "pinknoosoroibracelet",
    name: "ピンクのお揃いブレス",
    rarity: "PR",
    plan: "sense",
    idol: "sumika",
  },
  {
    id: 10,
    alias: "pinknoosoroibracelet_plus",
    name: "ピンクのお揃いブレス+",
    rarity: "PR+",
    plan: "sense",
    idol: "sumika",
  },
  {
    id: 11,
    alias: "chibidomotezukurimedal",
    name: "ちびども手作りメダル",
    rarity: "PR",
    plan: "logic",
    idol: "kotone",
  },
  {
    id: 12,
    alias: "chibidomotezukurimedal_plus",
    name: "ちびども手作りメダル+",
    rarity: "PR+",
    plan: "logic",
    idol: "kotone",
  },
  {
    id: 13,
    alias: "chouzetsuanminmask",
    name: "超絶あんみんマスク",
    rarity: "PR",
    plan: "logic",
    idol: "hiro",
  },
  {
    id: 14,
    alias: "chouzetsuanminmask_plus",
    name: "超絶あんみんマスク+",
    rarity: "PR+",
    plan: "logic",
    idol: "hiro",
  },
  {
    id: 15,
    alias: "midorinoosoroibracelet",
    name: "緑のお揃いブレス",
    rarity: "PR",
    plan: "logic",
    idol: "lilja",
  },
  {
    id: 16,
    alias: "midorinoosoroibracelet_plus",
    name: "緑のお揃いブレス+",
    rarity: "PR+",
    plan: "logic",
    idol: "lilja",
  },
  {
    id: 17,
    alias: "negaiwokanaeruomamori",
    name: "願いを叶えるお守り",
    rarity: "PR",
    plan: "logic",
    idol: "china",
  },
  {
    id: 18,
    alias: "negaiwokanaeruomamori_plus",
    name: "願いを叶えるお守り+",
    rarity: "PR+",
    plan: "logic",
    idol: "china",
  },
  {
    id: 19,
    alias: "technodog",
    name: "テクノドッグ",
    rarity: "PR",
    plan: "logic",
    idol: "ume",
  },
  {
    id: 20,
    alias: "technodog_plus",
    name: "テクノドッグ+",
    rarity: "PR+",
    plan: "logic",
    idol: "ume",
  },

  // PSR, PSR+

  {
    id: 21,
    alias: "sakinokanzenshokurecipe",
    name: "咲季の完全食レシピ",
    rarity: "PSR",
    plan: "sense",
    idol: "saki",
  },
  {
    id: 22,
    alias: "sakinokanzenshokurecipe_plus",
    name: "咲季の完全食レシピ+",
    rarity: "PSR+",
    idol: "saki",
    plan: "sense",
  },
  {
    id: 23,
    alias: "watashinohajimenogakufu",
    name: "私の「初」の楽譜",
    rarity: "PSR",
    plan: "sense",
    idol: "temari",
  },
  {
    id: 24,
    alias: "watashinohajimenogakufu_plus",
    name: "私の「初」の楽譜+",
    rarity: "PSR+",
    plan: "sense",
    idol: "temari",
  },
  {
    id: 25,
    alias: "dearlittleprince",
    name: "Dearリトルプリンス",
    rarity: "PSR",
    plan: "sense",
    idol: "mao",
  },
  {
    id: 26,
    alias: "dearlittleprince_plus",
    name: "Dearリトルプリンス+",
    rarity: "PSR+",
    plan: "sense",
    idol: "mao",
  },
  {
    id: 27,
    alias: "kimienosashiire",
    name: "きみへの差し入れ",
    rarity: "PSR",
    plan: "sense",
    idol: "rinami",
  },
  {
    id: 28,
    alias: "kimienosashiire_plus",
    name: "きみへの差し入れ+",
    rarity: "PSR+",
    plan: "sense",
    idol: "rinami",
  },
  {
    id: 29,
    alias: "houkagonorakugaki",
    name: "放課後のらくがき",
    rarity: "PSR",
    plan: "sense",
    idol: "sumika",
  },
  {
    id: 30,
    alias: "houkagonorakugaki_plus",
    name: "放課後のらくがき+",
    rarity: "PSR+",
    plan: "sense",
    idol: "sumika",
  },
  {
    id: 31,
    alias: "okininosneaker",
    name: "お気にのスニーカー",
    rarity: "PSR",
    plan: "logic",
    idol: "kotone",
  },
  {
    id: 32,
    alias: "okininosneaker_plus",
    name: "お気にのスニーカー+",
    rarity: "PSR+",
    plan: "logic",
    idol: "kotone",
  },
  {
    id: 33,
    alias: "daredemowakarunyuumonsho",
    name: "だれでもわかる入門書",
    rarity: "PSR",
    plan: "logic",
    idol: "hiro",
  },
  {
    id: 34,
    alias: "daredemowakarunyuumonsho_plus",
    name: "だれでもわかる入門書+",
    rarity: "PSR+",
    plan: "logic",
    idol: "hiro",
  },
  {
    id: 35,
    alias: "omoiderobot",
    name: "思い出ロボ",
    rarity: "PSR",
    plan: "logic",
    idol: "lilja",
  },
  {
    id: 36,
    alias: "omoiderobot_plus",
    name: "思い出ロボ+",
    rarity: "PSR+",
    plan: "logic",
    idol: "lilja",
  },
  {
    id: 37,
    alias: "shogenaihandkerchief",
    name: "しょげないハンカチ",
    rarity: "PSR",
    plan: "logic",
    idol: "china",
  },
  {
    id: 38,
    alias: "shogenaihandkerchief_plus",
    name: "しょげないハンカチ+",
    rarity: "PSR+",
    plan: "logic",
    idol: "china",
  },
  {
    id: 39,
    alias: "shibainupochette",
    name: "柴犬ポシェット",
    rarity: "PSR",
    plan: "logic",
    idol: "ume",
  },
  {
    id: 40,
    alias: "shibainupochette_plus",
    name: "柴犬ポシェット+",
    rarity: "PSR+",
    plan: "logic",
    idol: "ume",
  },

  // PSSR, PSSR+

  {
    id: 59,
    alias: "tomonitatakautowel",
    name: "共に戦うタオル",
    rarity: "PSSR",
    plan: "sense",
    idol: "saki",
  },
  {
    id: 60,
    alias: "tomonitatakautowel_plus",
    name: "共に戦うタオル+",
    rarity: "PSSR+",
    idol: "saki",
    plan: "sense",
  },
  {
    id: 61,
    alias: "jibunwomamoruearphone",
    name: "自分を守るイヤホン",
    rarity: "PSSR",
    plan: "sense",
    idol: "temari",
  },
  {
    id: 62,
    alias: "jibunwomamoruearphone_plus",
    name: "自分を守るイヤホン+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "temari",
  },
  {
    id: 63,
    alias: "uchinaruhikarinomimikazari",
    name: "内なる光の耳飾り",
    rarity: "PSSR",
    plan: "sense",
    idol: "mao",
  },
  {
    id: 64,
    alias: "uchinaruhikarinomimikazari_plus",
    name: "内なる光の耳飾り+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "mao",
  },
  {
    id: 65,
    alias: "toushindainoladylip",
    name: "等身大のレディリップ",
    rarity: "PSSR",
    plan: "sense",
    idol: "rinami",
  },
  {
    id: 66,
    alias: "toushindainoladylip_plus",
    name: "等身大のレディリップ+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "rinami",
  },
  {
    id: 67,
    alias: "gamecenternosenrihin",
    name: "ゲーセンの戦利品",
    rarity: "PSSR",
    plan: "sense",
    idol: "sumika",
  },
  {
    id: 68,
    alias: "gamecenternosenrihin_plus",
    name: "ゲーセンの戦利品+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "sumika",
  },
  {
    id: 69,
    alias: "saikounihappynominamoto",
    name: "最高にハッピーの源",
    rarity: "PSSR",
    plan: "sense",
    idol: "kotone",
  },
  {
    id: 70,
    alias: "saikounihappynominamoto_plus",
    name: "最高にハッピーの源+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "kotone",
  },
  {
    id: 71,
    alias: "saigononatsunoomoide",
    name: "最後の夏の思い出",
    rarity: "PSSR",
    plan: "sense",
    idol: "mao",
  },
  {
    id: 72,
    alias: "saigononatsunoomoide_plus",
    name: "最後の夏の思い出+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "mao",
  },
  {
    id: 73,
    alias: "pigdreamchokinbako",
    name: "ピッグドリーム貯金箱",
    rarity: "PSSR",
    plan: "logic",
    idol: "kotone",
  },
  {
    id: 74,
    alias: "pigdreamchokinbako_plus",
    name: "ピッグドリーム貯金箱+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "kotone",
  },
  {
    id: 75,
    alias: "michikusakenkyuunote",
    name: "みちくさ研究ノート",
    rarity: "PSSR",
    plan: "logic",
    idol: "hiro",
  },
  {
    id: 76,
    alias: "michikusakenkyuunote_plus",
    name: "みちくさ研究ノート+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "hiro",
  },
  {
    id: 77,
    alias: "yumeenolifelog",
    name: "夢へのライフログ",
    rarity: "PSSR",
    plan: "logic",
    idol: "lilja",
  },
  {
    id: 78,
    alias: "yumeenolifelog_plus",
    name: "夢へのライフログ+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "lilja",
  },
  {
    id: 79,
    alias: "himitsutokkuncardigan",
    name: "ひみつ特訓カーデ",
    rarity: "PSSR",
    plan: "logic",
    idol: "china",
  },
  {
    id: 80,
    alias: "himitsutokkuncardigan_plus",
    name: "ひみつ特訓カーデ+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "china",
  },
  {
    id: 81,
    alias: "koregawatashi",
    name: "これが、私",
    rarity: "PSSR",
    plan: "logic",
    idol: "temari",
  },
  {
    id: 82,
    alias: "koregawatashi_plus",
    name: "これが、私+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "temari",
  },
  {
    id: 83,
    alias: "korogaritsuzukerugenkinominamoto",
    name: "転がり続ける元気の源",
    rarity: "PSSR",
    plan: "logic",
    idol: "ume",
  },
  {
    id: 84,
    alias: "korogaritsuzukerugenkinominamoto_plus",
    name: "転がり続ける元気の源+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "ume",
  },
  {
    id: 85,
    alias: "kachienokodawari",
    name: "勝ちへのこだわり",
    rarity: "PSSR",
    plan: "logic",
    idol: "saki",
  },
  {
    id: 86,
    alias: "kachienokodawari_plus",
    name: "勝ちへのこだわり+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "saki",
  },
  {
    id: 87,
    alias: "kaerujirushinosenpuuki",
    name: "カエル印の扇風機",
    rarity: "PSSR",
    plan: "logic",
    idol: "sumika",
  },
  {
    id: 88,
    alias: "kaerujirushinosenpuuki_plus",
    name: "カエル印の扇風機+",
    rarity: "PSSR+",
    plan: "logic",
    idol: "sumika",
  },
  {
    id: 101,
    alias: "kimitowakeaunatsu",
    name: "きみと分け合う夏",
    rarity: "PSSR",
    plan: "sense",
    idol: "rinami",
  },
  {
    id: 102,
    alias: "kimitowakeaunatsu_plus",
    name: "きみと分け合う夏+",
    rarity: "PSSR+",
    plan: "sense",
    idol: "rinami",
  },

  // SPSSR

  {
    id: 89,
    alias: "etainoshirenaimono",
    name: "得体のしれないモノ",
    rarity: "SPSSR",
  },
  {
    id: 90,
    alias: "hoshinolittleprince",
    name: "星のリトルプリンス",
    rarity: "SPSSR",
  },
  {
    id: 91,
    alias: "kuyashisanoshouchou",
    name: "悔しさの象徴",
    rarity: "SPSSR",
  },
  {
    id: 92,
    alias: "kumoriwonuguttatowel",
    name: "曇りをぬぐったタオル",
    rarity: "SPSSR",
  },
  {
    id: 93,
    alias: "scoutsaegiribou",
    name: "スカウト遮り帽",
    rarity: "SPSSR",
  },
  {
    id: 95,
    alias: "mankaipairhairpin",
    name: "満開ペアヘアピン",
    rarity: "SPSSR",
  },
  {
    id: 96,
    alias: "nakanaorinokikkake",
    name: "仲直りのきっかけ",
    rarity: "SPSSR",
  },
  {
    id: 97,
    alias: "yumeniafuretaoonimotsu",
    name: "夢にあふれた大荷物",
    rarity: "SPSSR",
  },
  {
    id: 98,
    alias: "amakawaramenmeguri",
    name: "天川ラーメン巡り",
    rarity: "SPSSR",
  },
  {
    id: 99,
    alias: "nijikakerucloth",
    name: "虹かけるクロス",
    rarity: "SPSSR",
  },
  {
    id: 100,
    alias: "makezugirainokunshou",
    name: "負けず嫌いの勲章",
    rarity: "SPSSR",
    plan: "logic",
  },

  // NSR

  {
    id: 41,
    alias: "misuzukaranookurimono",
    name: "美鈴からの贈り物",
    rarity: "NSR",
  },
  {
    id: 42,
    alias: "datoukondeneinenshizaihou",
    name: "打倒！墾田永年私財法",
    rarity: "NSR",
  },
  {
    id: 43,
    alias: "tezukurinogohoubi",
    name: "手作りのご褒美",
    rarity: "NSR",
  },
  {
    id: 44,
    alias: "fuwafuwademokomoko",
    name: "ふわふわでもこもこ",
    rarity: "NSR",
  },
  {
    id: 45,
    alias: "oneesamadaihyakka",
    name: "お姉さま大百科",
    rarity: "NSR",
  },
  {
    id: 46,
    alias: "reinossdnohimitsu",
    name: "例のSSDの秘密",
    rarity: "NSR",
  },
  {
    id: 47,
    alias: "isshoniohirunepotpourri",
    name: "一緒にお昼寝ポプリ",
    rarity: "NSR",
  },
  {
    id: 48,
    alias: "watashigamitsuketaitsuzaimemo",
    name: "私が見つけた逸材メモ",
    rarity: "NSR",
  },
  {
    id: 49,
    alias: "asaichinotasukebune",
    name: "朝一の助け舟",
    rarity: "NSR",
  },
  {
    id: 50,
    alias: "chikainohanabira",
    name: "誓いの花びら",
    rarity: "NSR",
  },
  {
    id: 51,
    alias: "doublebottle",
    name: "ダブルボトル",
    rarity: "NSR",
    plan: "sense",
  },
  {
    id: 52,
    alias: "sakiosusumemat",
    name: "咲季オススメマット",
    rarity: "NSR",
    plan: "logic",
  },
  {
    id: 103,
    alias: "kawaiikakushibathtowel",
    name: "可愛い隠しバスタオル",
    rarity: "NSR",
    plan: "logic",
  },

  // NSSR

  {
    id: 53,
    alias: "hatsuboshibrooch",
    name: "はつぼしブローチ",
    rarity: "NSSR",
  },
  {
    id: 54,
    alias: "hatsuboshibracelet",
    name: "はつぼしブレスレット",
    rarity: "NSSR",
  },
  {
    id: 55,
    alias: "hatsuboshitechou",
    name: "はつぼし手帳",
    rarity: "NSSR",
    plan: "sense",
  },
  {
    id: 56,
    alias: "hatsuboshitshirt",
    name: "はつぼしTシャツ",
    rarity: "NSSR",
    plan: "sense",
  },
  {
    id: 57,
    alias: "hatsuboshikeyholder",
    name: "はつぼしキーホルダー",
    rarity: "NSSR",
    plan: "logic",
  },
  {
    id: 58,
    alias: "mascothikounin",
    name: "マスコット（非公認）",
    rarity: "NSSR",
    plan: "logic",
  },
  {
    id: 94,
    alias: "shinrainoakashi",
    name: "信頼の証",
    rarity: "NSSR",
  },
];

export const ITEMS_BY_ID = ITEMS.reduce(
  (acc, cur) => ({
    ...acc,
    [cur.id]: cur,
  }),
  {}
);

export const MEMORABLE_ITEMS = ITEMS.filter(
  (item) => !["NSR", "NSSR"].includes(item.rarity)
);
